# Generated by Django 5.2 on 2025-06-07 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('andyayiti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
