# Generated by Django 5.2.2 on 2025-06-07 20:20

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('andyayiti', '0002_videopost_description_alter_blogpost_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(),
        ),
    ]
